# Generated by Django 5.2 on 2025-05-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
    ]
